apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "cloud-agent.fullname" . }}
  namespace: {{ template "cloud-agent.namespace" . }}
  labels:
    {{- include "cloud-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "cloud-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloud-agent.serviceAccountName" . }}
