apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "teamcity-cloud-agent-profile.fullname" . }}
  namespace: {{ template "teamcity-cloud-agent-profile.namespace" . }}
  labels:
    {{- include "teamcity-cloud-agent-profile.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["list", "get"]
