apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "teamcity-cloud-agent-profile.fullname" . }}
  namespace: {{ template "teamcity-cloud-agent-profile.namespace" . }}
  labels:
    {{- include "teamcity-cloud-agent-profile.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "teamcity-cloud-agent-profile.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teamcity-cloud-agent-profile.serviceAccountName" . }}
