{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamcity-cloud-agent-profile.serviceAccountName" . }}
  namespace: {{ template "teamcity-cloud-agent-profile.namespace" . }}
  labels:
    {{- include "teamcity-cloud-agent-profile.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
