{{- if .Values.serviceAccount.createToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity-cloud-agent-profile.serviceAccountName" . }}-token
  namespace: {{ template "teamcity-cloud-agent-profile.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "teamcity-cloud-agent-profile.serviceAccountName" . }}
  labels:
    {{- include "teamcity-cloud-agent-profile.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
