apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "teamcity-helm-agent-account.fullname" . }}
  namespace: {{ template "teamcity-helm-agent-account.namespace" . }}
  labels:
    {{- include "teamcity-helm-agent-account.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
  resources:
    - configmaps
    - cronjobs
    - deployments
    - ingresses
    - jobs
    - pods
    - replicasets
    - secrets
    - services
  verbs: ["*"]
