apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "teamcity-helm-agent-account.fullname" . }}
  namespace: {{ template "teamcity-helm-agent-account.namespace" . }}
  labels:
    {{- include "teamcity-helm-agent-account.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "teamcity-helm-agent-account.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teamcity-helm-agent-account.serviceAccountName" . }}
